In [3]:
import numpy as np

In [5]:
np.random.rand(4,2)

array([[0.5284305 , 0.428269  ],
       [0.40116882, 0.53300342],
       [0.55284135, 0.19453569],
       [0.04768476, 0.95008434]])

In [7]:
np.random.randint(7)

6

In [11]:
np.random.randint(7,size=(3,3))

array([[2, 0, 2],
       [3, 6, 1],
       [0, 4, 0]])

In [13]:
np.random.randint(4,7,size=(3,3))

array([[4, 4, 6],
       [6, 6, 4],
       [5, 6, 4]])

In [15]:
np.random.randint(-4,8,size=(3,3))

array([[ 4,  3,  5],
       [ 2,  6, -2],
       [-4,  0,  2]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [28]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [33]:
# Matrix with 0,1,9
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [40]:
output[1:-1,1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [44]:
b = a 
b[0] = 100
b

array([100,   2,   3])

In [46]:
a

array([100,   2,   3])

In [50]:
# Use .copy explicityly to copy the array
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [53]:
b[0] = 100
b

array([100,   2,   3])

In [55]:
a

array([1, 2, 3])

In [57]:
### Mathematics ###
a = np.array([1,2,3])
a

array([1, 2, 3])

In [59]:
a + a

array([2, 4, 6])

In [63]:
a / 2

array([0.5, 1. , 1.5])

In [65]:
a ** a

array([ 1,  4, 27], dtype=int32)

In [69]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
h1 = np.ones((2,4))
h2 = np.zeros((2,4))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [84]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')

In [86]:
filedata

array([-2147483648,           2,           3,           4,           5,
                 6,           7,           8,           9,          10])

In [88]:
# Boolean Masking and Advanced Indxing
filedata > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
filedata[filedata > 5]

array([ 6,  7,  8,  9, 10])

In [92]:
# You can index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,1,4,6]]

array([1, 2, 5, 7])