In [323]:
# NumPy Basics: Arrays and Vectorized Computation
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))


In [324]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 30 ms


In [325]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.21 s


In [326]:
data = np.random.randn(2, 3)
data

array([[ 0.24388116, -1.39780219,  0.41284768],
       [-0.1359261 ,  0.29436676, -0.11334238]])

In [327]:
data * 10

array([[  2.4388116 , -13.97802188,   4.12847681],
       [ -1.35926103,   2.94366764,  -1.13342379]])

In [328]:
data + data

array([[ 0.48776232, -2.79560438,  0.82569536],
       [-0.27185221,  0.58873353, -0.22668476]])

In [329]:
data.shape

(2, 3)

In [330]:
data.dtype

dtype('float64')

In [331]:
# Creating numpy array using python list
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [332]:
# Two Dimensional Array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [333]:
arr2.ndim

2

In [334]:
arr2.shape

(2, 4)

In [335]:
arr.dtype

dtype('int32')

In [336]:
arr2.dtype

dtype('int32')

In [337]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [338]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [339]:
np.empty((2,3,2))

array([[[7.7e-322, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]]])

In [340]:
# numpy a range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [341]:
# See Images for Functions

In [342]:
# Data Types for ndarrays
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [343]:
# Explicitly assigning data type
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [344]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype




dtype('int32')

In [345]:
# Changing DataType using astype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [346]:
# arr with float datatype
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype


dtype('float64')

In [347]:
#changeing arr to int32
arr = arr.astype(np.int32)
arr.dtype

dtype('int32')

In [348]:
# Converting Strig to float
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [349]:
# Converting float to int
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.float64)
numeric_strings.astype(np.int32)

array([ 1, -9, 42])

In [350]:
# You can also use another array’s dtype attribute
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [351]:
# Shortcut to refer dtype 
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [352]:
# Arithmetic with NumPy Arrays
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [353]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [354]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [355]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [356]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [357]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [358]:
# Boolean Array

In [359]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [360]:
# Basic Indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [361]:
# Indexing
arr[5]

5

In [362]:
# Slicing
arr[5:8]

array([5, 6, 7])

In [363]:
# Assigning value of 12 to the slice
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [364]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [365]:
# Slicing does not make a copy, changes in sliced array wil affect original array
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [366]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [367]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [368]:
# If you want a copy of a slice of an ndarray instead of a view, you
# will need to explicitly copy the array—for example,
# arr[5:8].copy().

In [369]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [370]:
# arr2d[0][2] == arr2d[0,2] - Both are equal
arr2d[0][2]

3

In [371]:
arr2d[0,2]

3

In [372]:
# 3d array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [373]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [374]:
# Saving old values before changing
old_values = arr3d[0].copy()


In [375]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [378]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [380]:
arr3d[1, 0]

array([7, 8, 9])

In [388]:
x = arr3d[1]
x[0,2]

9

In [390]:
# Indexing with slices
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [392]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [394]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [400]:
# Start from beginning till row  2(-1)

arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [402]:
#You can pass multiple slices just like you can pass multiple indexes:
# Rows from start to 2, Columns from 1 to end
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [404]:
# Row 1 Col: Start to 2 
arr2d[1,:2]

array([4, 5])

In [406]:
# All rows, colum start to 1
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [408]:
# Rows start to 2, col start to 1
arr2d[:2,:1]

array([[1],
       [4]])

In [411]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [417]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[-0.30207595, -0.8999923 , -1.00440771, -1.08007557],
       [ 0.81568931,  0.39111435,  0.52342718,  0.15915797],
       [-0.27221266, -0.24637284, -0.41675016,  1.26468291],
       [-1.54009734, -0.26646702,  0.5213313 ,  0.77499529],
       [ 1.73651378,  0.40949847, -0.04527117,  0.19678858],
       [-1.04935673, -0.5241849 ,  0.59511942,  1.44111982],
       [ 0.79234062, -0.90940282,  0.87787051, -0.29404659]])

In [419]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [420]:
data[names == 'Bob']

array([[-0.30207595, -0.8999923 , -1.00440771, -1.08007557],
       [-1.54009734, -0.26646702,  0.5213313 ,  0.77499529]])