#### **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np


2. Create a null vector of size 10 

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a vector with values ranging from 10 to 49

In [59]:
arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [61]:
arr1.shape

(40,)

5. Print the type of the previous array in question 3

In [8]:
arr1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [11]:
print (np.__version__)
print (np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ahmed.TOYOTA-CENTRAL/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ahmed.TOYOTA-CENTRAL/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ahmed.TOYOTA-CENTRAL/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\comp

7. Print the dimension of the array in question 3


In [62]:
arr1.ndim

1

8. Create a boolean array with all the True values

In [14]:
arr2 = np.array([1,2,3,4],dtype=bool)
arr2


array([ True,  True,  True,  True])

9. Create a two dimensional array




In [27]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print (arr3.ndim)


2


10. Create a three dimensional array



In [28]:
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr4.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [44]:
arr5 = np.arange(0,30)
arr6 = arr5[::-1]
print (arr6)


[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [58]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [51]:
arr8 = np.identity(3)
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [57]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(np.float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [64]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [66]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr3 = arr1 < arr2
arr3


array([[False,  True, False],
       [ True, False,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [73]:
arr = np.arange(0,10)
arr1 = arr[arr%2!=0]
arr1

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [79]:
arr = np.arange(0,10)
arr[arr%2!=0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [3]:
arr = np.arange(10)
print (arr)
arr[5:9] = 12

arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [123]:
arr = np.ones((5,5))

arr[1:-1,1:-1]=0
arr




array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [126]:
arr2d = np.array([[1, 2, 3],

                [4, 5, 6], 

                [7, 8, 9]])

arr2d[1,1]=12
arr2d



array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [131]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [183]:
arr = np.arange(0,9).reshape(3,3)
arr1 = arr[0:1,0:3]
print (arr1)



[[0 1 2]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [188]:
arr = np.arange(0,9).reshape(3,3)
arr1 = arr[1:2,1:2]
arr1


array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [193]:
arr = np.arange(0,9).reshape(3,3)
arr1 = arr[0:2,2:3]
arr1

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [229]:
arr = np.random.randint(100, size=100).reshape(10,10)
min_val = arr.min()
max_val = arr.max()
print (min_val, max_val)



0 98


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [230]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [232]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.isin(a,b)
c

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
cond = names == 'Will'
data[~cond]



array([[-0.89157951,  0.61511881,  0.59699537,  1.38352777],
       [ 0.2703976 ,  1.85967727, -0.05940521, -0.13088359],
       [-0.90028347, -0.00758059,  0.03118406,  0.59294459],
       [ 1.21681906, -0.4726944 , -0.79638195, -0.08791905],
       [-1.28991466, -1.30033178,  1.08590075, -0.54316647]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask = (names != 'Will') & (names != 'Joe')
data[mask]



array([[-0.02108565,  0.72780031,  0.98504941,  0.5800903 ],
       [ 1.78682298, -1.04380833, -0.27648845,  0.6717333 ]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [35]:
array = np.arange(1,16)
arr = array.reshape(5,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [40]:
array = np.arange(1,17)
arr=array.reshape(2,2,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [45]:
np.swapaxes(arr,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [56]:
arr = np.arange(10)
x= np.sqrt(arr)
x[x<0.5] = 0
x


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [6]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)

arr3=np.maximum(arr1,arr2)
arr3


array([-0.07446065,  0.6532725 ,  1.33437184,  0.6335862 ,  1.50929019,
        0.92890822,  1.1484255 , -0.52291324,  0.90791311,  0.98644293,
        0.05644382,  2.07025934])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names_unique = np.unique(names)
names_sorted = np.sort(names_unique)
names_sorted

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [76]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [89]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[:,2] = newColumn
sampleArray


array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [93]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [95]:
a = np.random.randn(20)
a.cumsum()

array([1.72959202, 2.71040045, 3.04600752, 3.12695668, 2.93306723,
       2.99377986, 2.62495748, 3.70456519, 3.42325463, 4.47225995,
       4.88591212, 3.81282438, 1.89872896, 3.31670451, 3.8678722 ,
       3.51061665, 3.83093289, 3.39561362, 4.30141573, 4.81219125])